export const PURPOSE_DATA = {
  "Officers / Official Visitors": {
    "CGST GHAZIABAD": [
      "CENTRAL DIARY AND DISPATCH",
      "GST SUVIDHA KENDRA",
      "RETIRESD OFFICERS ROOM",
      "COMMISSIONER",
      "ADDITIONAL/JOINT COMMISSIONER (ROOM 202)",
      "ADDITIONAL/JOINT COMMISSIONER (ROOM 203)",
      "ADDITIONAL/JOIN COMMISSIONER",
      "DY./ASST.COMMISSIONER, DIVISION-I",
      "DY./ASST.COMMISSIONER, DIVISION-II",
      "DY./ASST.COMMISSIONER, DIVISION-III",
      "DY./ASST.COMMISSIONER, DIVISION-IV",
      "DY./ASST.COMMISSIONER, DIVISION-V",
      "DY./ASST.COMMISSIONER, DIVISION-VI",
      "DY./ASST.COMMISSIONER, DIVISION-VII",
      "Library",
      "RANGES OF DIVISION-I",
      "RANGES OF DIVISION-II",
      "RANGES OF DIVISION-III",
      "RANGES OF DIVISION-IV",
      "RANGES OF DIVISION-V",
      "RANGES OF DIVISION-VI",
      "RANGE-31, 32 OF DIVISION-VII",
      "RANGE- 33, 34, 35 OF DIVISION-VII",
      "ANTI- EVASION",
      "SUPERINTENDENT ADJUDICATION",
      "SUPERINTENDENT HEADQUARTER",
      "SUPERINTENDENT INFRA-BUILDING",
      "SUPERINTENDENT ACCOUNTS",
      "SUPERINTENDENT ADMINISTRATION",
      "Other"
    ],
    "CCO, MEERUT ZONE MEERUT (CAMP OFFICE)": [
      "CHIEF COMMISSIONER (HAG+)",
      "ADDITIONAL/JOINT COMMISSIONER",
      "DY./ASSTT. COMMISSIONER",
      "SECRETERIATE (CCO)",
      "Other"
    ],
    "CGST AUDIT (MEERUT) CIRCLE GHAZIABAD": [
      "COMMISSIONER",
      "ADDITIONAL/JOINT COMMISSIONER",
      "DY./ASST.COMMISSIONER",
      "DY./ASST.COMMISSIONER, CIRCLE-4",
      "DY./ASST.COMMISSIONER, CIRCLE-5",
      "DY./ASST.COMMISSIONER, CIRCLE-6",
      "SUPERINTENDENT AUDIT CIRCLE- 4, 5, 6, 7",
      "Other"
    ],
    "COMMISSIONER APPEALS (CAMP OFFICE)": [
      "COMMISSIONER",
      "ADDITIONAL/JOINT COMMISSIONER",
      "DY./ASST.COMMISSIONER",
      "SUPERINTENDENT/INSPECTOR",
      "Other"
    ],
    "PAY & ACCOUNT OFFICE GHAZIABAD": [
      "PAO",
      "AAO/AD(OL)",
      "TAX ASSIATANT",
      "Other"
    ]
  },
  "Other Than Official": {
    "CPWD": ["Other"],
    "CONTRACTOR (housekeeping/security)": ["Other"],
    "MAINTENANCE (CGST BHAWAN)": ["Other"],
    "Other": ["Other"]
  }
};
